### PR TITLE
Check: make the warning stand out

### PR DESCRIPTION
**Pull request by vcunat**

### CODE REVIEW

**Comment by vcunat** [comment]
The warning really was too subtle visually, as pointed out by @mweinelt, e.g. see https://github.com/NixOS/nixpkgs/pull/314299

I haven't tested this, at least so far.

**Comment by mweinelt** [comment]
$\color{#FF0000}{WARNING:}$ :thinking:

**Comment by vcunat** [comment]
We're writing GitHub's markdown, so maybe this "Caution" thing?
https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts

**Comment by vcunat** [comment]
> [!CAUTION]
> a test defined in `passthru.tests` did not pass

**Comment by zowoq** [comment]
This is still a draft, is it ready to be merged?

**Comment by mweinelt** [comment]
It should be.

**Comment by vcunat** [comment]
(I haven't tested this in any way.)

**Comment by zowoq** [comment]
I'll deploy it now and keep checking the logs until the bot opens a PR with a failed test that I can link here.

**Comment by zowoq** [comment]
Didn't take long: https://github.com/NixOS/nixpkgs/pull/302140#issuecomment-2298561723.

**Pull request merged**
